config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'villages/create'
  get 'families/paper', to: 'families#paper'
  root 'home#index'
  get '/', to: 'home#index'
  get 'welcome', to: 'home#hello'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :donations
  resources :families
  resources :village_donations
  resources :patrol_members
  resources :villages
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :village
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
  end

  def paper
    @families = current_user.manage_village.families
    @dates = Time.days_in_month(10, 2021)
    qrcode = RQRCode::QRCode.new("http://github.com/")
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true
    )

    respond_to do |format|
      # some other formats like: format.html { render :show }
      format.html { render :paper }

      format.pdf do
        pdf = FamilyPdf.new
        send_data pdf.render,
                  filename: "export.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: "Family was successfully created." }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: "Family was successfully updated." }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: "Family was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.fetch(:family, {})
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_with(model: family) do |form| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keluarga</h1>

<div class="flex flex-col mt-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Nama
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Lokasi
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Detail
            </th>
            <th scope="col" class="relative px-6 py-3">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
          <% @families.each do |family| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="text-sm font-medium text-gray-900">
                    <%= family.householder %>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= "No. #{family.number} RT #{family.rt} RW #{family.rw}" %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= family.detail %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <%= link_to 'Show', family, class: 'text-blue-600 hover:text-blue-900' %>
                <%= link_to 'Edit', edit_family_path(family), class: 'text-indigo-600 hover:text-indigo-900' %>
                <%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-600 hover:text-red-900' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/paper.html.erb
<p id="notice"><%= notice %></p>

<h1>Desain kertas jimpitan</h1>

<div class="flex justify-between">
  <div></div>
  <%= link_to "Cetak kertas jimpitan", families_paper_path(format: :pdf), class: 'inline-block mt-6 px-4 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700' %>
</div>

<div class="flex justify-center space-x-4 mt-4">
  <div class="align-middle inline-block sm:px-6 lg:px-8">
    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
      <table class="divide-y divide-x divide-gray-200">
        <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-3 py-2 uppercase tracking-wider">
            Tanggal
          </th>
          <th scope="col" class="px-3 py-2 uppercase tracking-wider">
            Oktober
          </th>
        </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
        <% @dates.times do |date| %>
          <tr class="text-center">
            <td class="px-3 py-2 border-r">
              <%= date + 1 %>
            </td>
            <td class="px-3 py-2">
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div>
    <p>QR code</p>
    <div class="mt-4">
      <%= @svg.html_safe %>
    </div>
  </div>
</div>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>