config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'villages/create'
  get 'families/paper', to: 'families#paper'
  root 'home#index'
  get '/', to: 'home#index'
  get 'welcome', to: 'home#hello'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :donations
  resources :families
  resources :village_donations
  resources :patrol_members
  resources :villages
end

app/models/patrol_member.rb
class PatrolMember < ApplicationRecord
  belongs_to :village
  belongs_to :user

  enum day_in_week: [:sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday]
end

app/controllers/patrol_members_controller.rb
class PatrolMembersController < ApplicationController
  before_action :set_patrol_member, only: %i[ show edit update destroy ]

  # GET /patrol_members or /patrol_members.json
  def index
    @patrol_members = PatrolMember.where(village_id: current_user.manage_village.id).all
  end

  # GET /patrol_members/1 or /patrol_members/1.json
  def show
  end

  # GET /patrol_members/new
  def new
    @patrol_member = PatrolMember.new
  end

  # GET /patrol_members/1/edit
  def edit
  end

  # POST /patrol_members or /patrol_members.json
  def create
    @patrol_member = PatrolMember.new(patrol_member_params)

    respond_to do |format|
      if @patrol_member.save
        format.html { redirect_to @patrol_member, notice: "Patrol member was successfully created." }
        format.json { render :show, status: :created, location: @patrol_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patrol_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patrol_members/1 or /patrol_members/1.json
  def update
    respond_to do |format|
      if @patrol_member.update(patrol_member_params)
        format.html { redirect_to @patrol_member, notice: "Patrol member was successfully updated." }
        format.json { render :show, status: :ok, location: @patrol_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patrol_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patrol_members/1 or /patrol_members/1.json
  def destroy
    @patrol_member.destroy
    respond_to do |format|
      format.html { redirect_to patrol_members_url, notice: "Patrol member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patrol_member
      @patrol_member = PatrolMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patrol_member_params
      params.require(:patrol_member).permit(:village_id, :user_id, :day_in_week)
    end
end

app/helpers/patrol_members_helper.rb
module PatrolMembersHelper
end

app/views/patrol_members/_form.html.erb
<%= form_with(model: patrol_member) do |form| %>
  <% if patrol_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patrol_member.errors.count, "error") %> prohibited this patrol_member from being saved:</h2>

      <ul>
        <% patrol_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :village_id, value: current_user.manage_village.id %>

  <div class="mt-3">
    <%= form.label :user_id, class: 'block' %>
    <%= form.select :user_id, options_from_collection_for_select(User.all, :id, :email), class: 'mt-2' %>
  </div>

  <div class="mt-3">
    <%= form.label :day_in_week, class: 'block' %>
    <%= form.select :day_in_week, PatrolMember.day_in_weeks.map { |k, v| [ k, k ] }, class: 'mt-2' %>
  </div>

  <div class="mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/patrol_members/edit.html.erb
<h1>Editing Patrol Member</h1>

<%= render 'form', patrol_member: @patrol_member %>

<%= link_to 'Show', @patrol_member %> |
<%= link_to 'Back', patrol_members_path %>

app/views/patrol_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anggota ronda</h1>

<div class="flex flex-col mt-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Nama
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Hari
            </th>
            <th scope="col" class="relative px-6 py-3">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
          <% @patrol_members.each do |patrol_member| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="text-sm font-medium text-gray-900">
                    <%= patrol_member.user.name %>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= patrol_member.day_in_week %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <%= link_to 'Show', patrol_member, class: 'text-blue-600 hover:text-blue-900' %>
                <%= link_to 'Edit', edit_patrol_member_path(patrol_member), class: 'text-indigo-600 hover:text-indigo-900' %>
                <%= link_to 'Destroy', patrol_member, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-600 hover:text-red-900' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'New Patrol Member', new_patrol_member_path %>

app/views/patrol_members/new.html.erb
<h1>New Patrol Member</h1>

<%= render 'form', patrol_member: @patrol_member %>

<%= link_to 'Back', patrol_members_path %>

app/views/patrol_members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_patrol_member_path(@patrol_member) %> |
<%= link_to 'Back', patrol_members_path %>