config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'villages/create'
  get 'families/paper', to: 'families#paper'
  root 'home#index'
  get '/', to: 'home#index'
  get 'welcome', to: 'home#hello'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :donations
  resources :families
  resources :village_donations
  resources :patrol_members
  resources :villages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :village
  belongs_to :user

  enum status: [:present, :sick, :permit, :alpha]
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :village
  belongs_to :family
  belongs_to :patrol_member
  belongs_to :village_donation
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :village
end

app/models/patrol_member.rb
class PatrolMember < ApplicationRecord
  belongs_to :village
  belongs_to :user

  enum day_in_week: [:sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday]
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  class << self
    %w[admin manager member guest].each do |name|
      define_method name do
        find_by(name: name)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_detail
  has_many :village_managers
  has_many :patrol_members
  has_many :manage_villages, through: :village_managers, source: :village
  belongs_to :role

  alias_attribute :detail, :user_detail
  alias_attribute :managers, :village_managers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  after_initialize :set_default_role
  before_create :set_default_user_detail

  def set_default_role
    self.role_id ||= Role.guest.id
  end

  def name
    detail.name
  end

  def set_default_user_detail
    self.build_user_detail(name: "orang baru #{rand(1111...9999)}") if self.detail.nil?
  end

  def is_new
    managers.blank? and patrol_members.blank?
  end

  def is_manager
    role_id == Role.manager.id
  end

  def has_village_to_manage
    managers.present?
  end

  def manage_village
    manage_villages.first
  end
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
end

app/models/village.rb
class Village < ApplicationRecord
  has_many :families
  has_many :village_managers
  has_many :village_donations
  has_many :patrol_members

  alias_attribute :managers, :village_managers

  def ready_to_print
    patrol_members.present? and village_donations.present?
  end
end

app/models/village_donation.rb
class VillageDonation < ApplicationRecord
  belongs_to :village

  enum content: [:empty, :money, :rice, :other]
end

app/models/village_manager.rb
class VillageManager < ApplicationRecord
  belongs_to :village
  belongs_to :user

  alias_attribute :manager, :user
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
  end

  def paper
    @families = current_user.manage_village.families
    @dates = Time.days_in_month(10, 2021)
    qrcode = RQRCode::QRCode.new("http://github.com/")
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true
    )

    respond_to do |format|
      # some other formats like: format.html { render :show }
      format.html { render :paper }

      format.pdf do
        pdf = FamilyPdf.new
        send_data pdf.render,
                  filename: "export.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: "Family was successfully created." }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: "Family was successfully updated." }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: "Family was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.fetch(:family, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'welcome' unless user_signed_in?

    @village = Village.new
  end

  def create

  end

  def welcome
  end
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  def create
    @village = Village.new(village_params)
    if @village.save
      @village.managers.create(user_id: current_user.id)
      current_user.role = Role.manager
      current_user.save
      redirect_to root_path, notice: 'Desa berhasil dibuat.'
    else
      redirect_to root_path, alert: 'Gagal membuat desa baru.'
    end
  end

  private

  def village_params
    params.require(:village).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patrol_members_helper.rb
module PatrolMembersHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/layouts/_header.html.erb
<div class="relative pt-6 px-4 sm:px-6 lg:px-8">
  <nav class="relative flex items-center justify-between sm:h-10" aria-label="Global">
    <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
      <div class="flex items-center justify-between w-full md:w-auto">
        <a href="/">
          <span class="sr-only">Workflow</span>
          <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg">
        </a>
        <div class="-mr-2 flex items-center md:hidden">
          <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <!-- Heroicon name: outline/menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <div class="hidden md:flex justify-center md:ml-10 md:pr-4 md:space-x-8">
      <div class="inline-flex space-x-4 justify-between">
        <% if user_signed_in? %>
          <%= link_to "Anggota", patrol_members_path, class: 'font-medium text-gray-500 hover:text-gray-900' %>
          <%= link_to "Bentuk Sumbangan", village_donations_path, class: 'font-medium text-gray-500 hover:text-gray-900' %>
          <%= link_to "Keluarga", families_path, class: 'font-medium text-gray-500 hover:text-gray-900' %>
          <%= link_to "Sumbangan", donations_path, class: 'font-medium text-gray-500 hover:text-gray-900' %>
          <%= link_to "Presensi", families_path, class: 'font-medium text-gray-500 hover:text-gray-900' %>
        <% end %>
        <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Bantuan</a>
      </div>
      <div class="inline-flex space-x-4 justify-between">
        <% if user_signed_in? %>
          <%= link_to current_user.name, destroy_user_session_path, method: :delete, class: 'font-medium text-indigo-600 hover:text-indigo-500' %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'font-medium text-red-600 hover:text-red-500' %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="id">
<head>
  <title>JimpitanRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto">
    <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:w-full lg:pb-28 xl:pb-32">
      <div>
        <%= render 'layouts/header' %>
        <main class="mx-auto max-w-7xl px-4 mt-6 sm:px-6 lg:px-8">
          <% flash.each do |type, message| %>
            <% if type == :error %>
              <div class="text-red-500"><%= message %></div>
            <% else %>
              <div class="text-indigo-500"><%= message %></div>
            <% end %>
          <% end %>
          <%= yield %>
        </main>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="id">
<head>
  <title>Home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto">
    <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:w-full lg:pb-28 xl:pb-32">

      <div>
        <%= render 'layouts/header' %>
        <main class="mx-auto max-w-7xl px-4 mt-6 sm:px-6 lg:px-8">
          <% flash.each do |type, message| %>
            <% if type == :error %>
              <div class="text-red-500"><%= message %></div>
            <% else %>
              <div class="text-indigo-500"><%= message %></div>
            <% end %>
          <% end %>
          <%= yield %>
        </main>
      </div>
    </div>
  </div>
</div>

</body>
</html>